-- Migration: Create Audit Logs table and security RLS policies
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references public.profiles(id) on delete set null,
  user_email text,
  action text not null,
  ip_address text,
  user_agent text,
  location text,
  path text,
  method text,
  details jsonb default '{}'::jsonb
);

-- Indexing for high performance queries & filters
create index if not exists idx_audit_logs_created_at on public.audit_logs(created_at desc);
create index if not exists idx_audit_logs_action on public.audit_logs(action);
create index if not exists idx_audit_logs_ip_address on public.audit_logs(ip_address);
create index if not exists idx_audit_logs_user_id on public.audit_logs(user_id);

-- Enable Row Level Security (RLS)
alter table public.audit_logs enable row level security;

-- Policy: Admins can view all audit logs
create policy "Admins can view audit logs"
  on public.audit_logs for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Policy: Allow inserts from authenticated users or service role
create policy "Allow insert for audit logs"
  on public.audit_logs for insert
  with check (true);
